"""Run the sample analytical queries in sql/analytics/ against warehouse.duckdb.

Usage:
    python run_queries.py               # print every query's result
    python run_queries.py q06           # print only queries whose file name starts with q06
    python run_queries.py --markdown    # also (re)write docs/sample_query_results.md

Run `python build.py` first to create the warehouse.
"""
from __future__ import annotations

import sys
from decimal import Decimal
from pathlib import Path

import duckdb

ROOT = Path(__file__).parent
DB_PATH = ROOT / "warehouse.duckdb"
QUERY_DIR = ROOT / "sql" / "analytics"
RESULTS_MD = ROOT / "docs" / "sample_query_results.md"


def fmt(value, decimals: int = 0) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return str(value).lower()
    if isinstance(value, int):
        return f"{value:,}"
    if isinstance(value, (float, Decimal)):
        return f"{float(value):,.{decimals}f}"
    return str(value)


def column_decimals(values: list) -> int:
    """Fewest decimals (0-2) that show every value in the column, so a column reads uniformly."""
    needed = 0
    for v in values:
        if isinstance(v, (float, Decimal)) and not isinstance(v, bool):
            for d in (0, 1, 2):
                if round(float(v), d) == round(float(v), 2):
                    needed = max(needed, d)
                    break
    return needed


def split_header(sql: str) -> tuple[str, list[str]]:
    """Return (title, description lines) from the leading '-- ' comment block."""
    lines: list[str] = []
    for line in sql.splitlines():
        if not line.startswith("--"):
            break
        body = line[2:]
        is_continuation = body.startswith("  ") and lines  # 'Technique:' text wraps with deeper indent
        if is_continuation:
            lines[-1] += " " + body.strip()
        else:
            lines.append(body.strip())
    title = lines[0].split("|", 1)[-1].strip() if lines else ""
    return title, lines[1:]


def text_table(columns: list[str], rows: list[list[str]], numeric: list[bool]) -> str:
    widths = [max(len(c), *(len(r[i]) for r in rows)) if rows else len(c) for i, c in enumerate(columns)]
    def line(cells):
        return "  ".join(c.rjust(w) if numeric[i] else c.ljust(w) for i, (c, w) in enumerate(zip(cells, widths)))
    rule = "  ".join("-" * w for w in widths)
    return "\n".join([line(columns), rule, *(line(r) for r in rows)])


def markdown_table(columns: list[str], rows: list[list[str]], numeric: list[bool]) -> str:
    head = "| " + " | ".join(columns) + " |"
    sep = "| " + " | ".join("---:" if n else "---" for n in numeric) + " |"
    body = ["| " + " | ".join(r) + " |" for r in rows]
    return "\n".join([head, sep, *body])


def main(argv: list[str]) -> int:
    write_md = "--markdown" in argv
    prefixes = [a for a in argv if not a.startswith("--")]

    if not DB_PATH.exists():
        print("warehouse.duckdb not found - run `python build.py` first.", file=sys.stderr)
        return 1

    files = sorted(QUERY_DIR.glob("q*.sql"))
    if prefixes:
        files = [f for f in files if any(f.name.startswith(p) for p in prefixes)]

    con = duckdb.connect(str(DB_PATH), read_only=True)
    md = [
        "# Sample query results",
        "",
        "Generated by `python run_queries.py --markdown` from the synthetic dataset in `data/raw/`. "
        "Do not edit by hand. Figures illustrate the model; they are not real market data.",
        "",
    ]
    for path in files:
        sql = path.read_text(encoding="utf-8")
        title, description = split_header(sql)
        cursor = con.execute(sql)
        columns = [d[0] for d in cursor.description]
        raw_rows = cursor.fetchall()
        decimals = [column_decimals([r[i] for r in raw_rows]) for i in range(len(columns))]
        rows = [[fmt(v, decimals[i]) for i, v in enumerate(r)] for r in raw_rows]
        numeric = [all(isinstance(r[i], (int, float, Decimal)) and not isinstance(r[i], bool)
                       for r in raw_rows if r[i] is not None) and any(r[i] is not None for r in raw_rows)
                   for i in range(len(columns))]

        print(f"\n== {path.stem.upper()[:3]} | {title} ({len(rows)} rows) ==")
        print(text_table(columns, rows, numeric))

        md += [
            f"## {path.stem[:3].upper()} - {title}",
            "",
            *[f"**{label}:** {rest.strip()}\n" for label, _, rest in (d.partition(":") for d in description)],
            markdown_table(columns, rows, numeric),
            "",
            f"Source: [`sql/analytics/{path.name}`](../sql/analytics/{path.name})",
            "",
        ]

    if write_md:
        RESULTS_MD.parent.mkdir(exist_ok=True)
        RESULTS_MD.write_text("\n".join(md), encoding="utf-8", newline="\n")
        print(f"\nwrote {RESULTS_MD.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
